version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://username:password@db:5432/database"
    volumes:
      - .:/app
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "database"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
